package com.oracle.cloud.demo.oe.sessions;

import com.oracle.cloud.demo.oe.dto.BasketItem;
import com.oracle.cloud.demo.oe.entities.Customer;
import com.oracle.cloud.demo.oe.entities.Order;
import com.oracle.cloud.demo.oe.entities.OrderItem;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;

@Stateless
public class CheckoutBean implements CheckoutFacade {

    @EJB
    private CustomersFacade customersFacade;

    @EJB
    private OrdersFacade ordersFacade;

    @EJB
    private OrderItemsFacade orderItemsFacade;

    @Override
    public Order checkout(String user, List<BasketItem> basketItems) {
        String userEmail = user;

        Customer cust = customersFacade.getCustomerByEmail(userEmail);

        BigDecimal total = calculateTotal(basketItems);

        Order order = new Order(cust,
                Calendar.getInstance(),
                null,
                total);

        ordersFacade.create(order);

        for (BasketItem basketItem : basketItems) {
            OrderItem orderItem = new OrderItem(null,// ID auto generated by SEQ
                    order,
                    basketItem.getProduct(),
                    basketItem.getQuantity(),
                    basketItem.getSubtotal());
            orderItemsFacade.create(orderItem);
        }

        return order;
    }

    private BigDecimal calculateTotal(List<BasketItem> basketItems) {
        BigDecimal total = BigDecimal.ZERO;
        for (BasketItem bi : basketItems) {
            total = total.add(bi.getSubtotal());
        }
        return total;
    }

}
