#!/bin/sh
#
# Util script to run WLST on a remote machine
# 
# Inform user (usually 'opc'), ipaddress, and domain location of remote WebLogic server
#
REMOTE_USER=opc
REMOTE_SERVER=129.152.129.211
REMOTE_DOMAIN_HOME=/home/bruno/Work/tools/oracle/mw1212/user_projects/domains/base_domain
DIR="$( cd "$( dirname "$0" )" && pwd )"
PRIVATE_KEYFILE=$DIR/../ssh/hol9458_id_rsa
KEY_PARAM='-i $PRIVATE_KEYFILE'

# Test
REMOTE_USER=bruno
REMOTE_SERVER=localhost
KEY_PARAM=''

# Copy WLST script to remote server
scp $1 $REMOTE_USER@$REMOTE_SERVER:/tmp/$1

# Execute WLST script on remote server
ssh $REMOTE_USER@$REMOTE_SERVER $KEY_PARAM DOMAIN_HOME=$REMOTE_DOMAIN_HOME TEMP_WLST_SCRIPT=/tmp/$1 '/bin/bash -s' <<'ENDSSHSESSION'
  cd $DOMAIN_HOME/bin
  source setDomainEnv.sh
  java weblogic.WLST -skipWLSModuleScanning $TEMP_WLST_SCRIPT
  rm $TEMP_WLST_SCRIPT
ENDSSHSESSION
